/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#007025",
        "surface-dim": "#d8dad9",
        "surface-container-high": "#e6e9e7",
        "surface-variant": "#e1e3e1",
        "primary-fixed-dim": "#64df72",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#53e23d",
        "on-tertiary-fixed-variant": "#00522d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#81fc8b",
        "surface-bright": "#f8faf8",
        "inverse-on-surface": "#eff1ef",
        "on-primary-fixed-variant": "#005319",
        "tertiary-fixed-dim": "#86d8a1",
        "inverse-surface": "#2e3130",
        "outline": "#6f7a70",
        "surface-container": "#eceeec",
        "secondary-container": "#6efd55",
        "inverse-primary": "#64df72",
        "tertiary-fixed": "#a1f5bc",
        "on-surface-variant": "#3f4941",
        "surface-container-highest": "#e1e3e1",
        "on-secondary-fixed-variant": "#045300",
        "on-primary": "#ffffff",
        "surface": "#f8faf8",
        "secondary": "#076e00",
        "on-primary-fixed": "#002106",
        "secondary-fixed": "#78ff5f",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#00210f",
        "on-surface": "#191c1b",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc9be",
        "tertiary-container": "#166e41",
        "background": "#f8faf8",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#012200",
        "on-primary-container": "#7af585",
        "on-tertiary-container": "#9aedb5",
        "on-secondary-container": "#087300",
        "surface-tint": "#006e24",
        "primary": "#00551a",
        "tertiary": "#00542e",
        "surface-container-low": "#f2f4f2",
        "on-background": "#191c1b"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [],
}
